### ISSUE TITLE
TODO After code review

### ISSUE THREAD

**Issue by tmarciszewski** [tmarciszewski/spotify-browser#1]
- [ ] Rethink project structure
- [ ] Add modules (for science!)
- [ ] Show ```async``` functionality
- [x] Consolidate subscriptions to route.params into one and make it more readable
- [x] Move rx operator imports to (maybe) ```polyfills.ts```
- [x] Check for subscription/unsubscription to observables other than http service and ActivatedRoute
- [x] Make imports uniform - use `'` instead of `"` and check spacing
